### ISSUE TITLE
Export images?

### ISSUE THREAD

**Issue by alelordelo** [acwright/ImportExport#4]
Thanks for such a great and detailed tutorial!

I am trying to get export working with images, but got some hiccups... : )

Do you know how to do out? I posted on SO bellow:
https://stackoverflow.com/questions/65993146/swiftui-2-0-export-images-with-fileexporter-modifier

**Comment by acwright** [comment]
You will need to make a custom FileDocument type that wraps your image.

**Comment by alelordelo** [comment]
Are you sure? no idea how to do that....

 Isn't it possible to just specify an image?

**Comment by acwright** [comment]
Yes I'm sure. Please see https://developer.apple.com/documentation/swiftui/filedocument
