### ISSUE TITLE
 Export multiple files

### ISSUE THREAD

**Issue by alelordelo** [acwright/ImportExport#5]
HI Aaron,

Did you manage to export multiple files?

I am tying to export multiple images, but only got it to work in MacOS. On iOS it exports only 1 image...

https://stackoverflow.com/questions/67336152/swiftui-fileexporter-exporting-only-1-document

**Comment by acwright** [comment]
Take a look at the documentation for `FileWrapper`:

https://developer.apple.com/documentation/foundation/filewrapper

You can only return ONE instance of FileWrapper from `fileWrapper(configuration: WriteConfiguration) throws -> FileWrapper` BUT a `FileWrapper` instance can represent (wrap) more than one file. 

Try creating a FileWrapper that is a directory (folder) and exporting the directory of images.
